# Site settings
title: 光阴的故事
header-img: img/home-bg.jpg
email: cundong.liu@mail.com
description: "少年图"
baseurl: "http://www.liuyanzhe.com"
url: "http://www.liuyanzhe.com"
twitter_username: cundong
github_username:  cundong
facebook_username:  liucundong

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
